### ISSUE TITLE
Move 0D documentation to the simvascular website

### ISSUE THREAD

**Issue by menon-karthik** [SimVascular/simvascular.github.io#31]
### Use Case

After discussion with @alisonmarsden and @ktbolt, we have decided to move the documentation relevant to end-users to the Simvascular website. Details related to the code, API, etc. will still be on the Github repo for users who are interested in digging in further. 

I will move user guides for svZeroDSolver, svZeroDCalibrator, and the GUIs (?) to the SV website. I will also move the theory on the overall governing equations, time integration, etc. Details for each block, which are built using Doxygen, will stay on Github. I will reference some of the important blocks from the SV website so users know how to find the information if they want to. 

### Problem

N/A

### Solution

N/A

### Alternatives considered

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by ktbolt** [comment]
@menon-karthik I've looked at your updates, a good start!

<img width="500" alt="Screenshot 2024-10-11 at 10 22 27 AM" src="https://github.com/user-attachments/assets/4d72eec9-1513-4d79-be8a-046f3b594f50">

Some comments

- Move the **Theory** section to the top 
- Use bullets for `noteworthy features`, `categories of blocks`, etc.
- Make sub-sections (e.g. Configuration) visible from the `0D Solver` menu
- Add a `Running svZeroDSolver` section. The`Installation` sub-section should just be links to SimTK (for installing) or svZerorDSolver GitHub (for building). See svFSIplus running-simulation sub-section.
- Move `Blocks` to the `Developer Guide` sub-section
- The `Configuration` section should be called `Input file format` 
- Describe and provide a link to what JSON is
- The input file parameter descriptions could be more detailed, what is `fn: Mathematical expression` ?
-  Architecture should be under `Developer Guide` and please don't use the `robust architecture` phrase.

I'm surprised to see `svZeroDGUI` and `svZeroDVisualization` installed under svZeroDSolver, guess I wasn't paying attention to the Issues for this!

The documentation for these guys needs to be very detailed because they require a bunch of other software installed to run.

**Comment by menon-karthik** [comment]
@ktbolt Thanks for your comments!

> @menon-karthik I've looked at your updates, a good start!
> <img alt="Screenshot 2024-10-11 at 10 22 27 AM" width="500" src="https://private-user-images.githubusercontent.com/23109458/375839209-4d72eec9-1513-4d79-be8a-046f3b594f50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NzUyMTMsIm5iZiI6MTcyODY3NDkxMywicGF0aCI6Ii8yMzEwOTQ1OC8zNzU4MzkyMDktNGQ3MmVlYzktMTUxMy00ZDc5LWJlOGEtMDQ2ZjNiNTk0ZjUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDE5MjgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxMzM3YWJlMThjNGNjM2U5Mzc3ZTEyOTY4NmRmNWE1MGQ1Y2Y1ZDM1YWIxMTM1ZDQzODJhNjUxYmE4ZmY3ODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8brX7NwuaCAV99hjj0EZoccDspAfp7L57QMOxrwhI0U">
> 
> Some comments
> 
>     * Move the **Theory** section to the top

Done

> 
>     * Use bullets for `noteworthy features`, `categories of blocks`, etc.

I am actually using bullet points but for some reason they are not rendering correctly. I thought it had something to do with how I'm rendering locally, but sounds like it is not rendering correctly for you either. I will dig into this...

> 
>     * Make sub-sections (e.g. Configuration) visible from the `0D Solver` menu

Done 

> 
>     * Add a `Running svZeroDSolver` section. The`Installation` sub-section should just be links to SimTK (for installing) or svZerorDSolver GitHub (for building). See svFSIplus running-simulation sub-section.

Done. I retained the pip and CMake install instructions because they are required for users who want to use the Python API and C++ interface. They are also probably easier for most users (especially pip) than the SimTK installer. 

> 
>     * Move `Blocks` to the `Developer Guide` sub-section

I think this might be good to have in the user docs because we keep referring to the term Blocks everywhere and I thought having a section on what we mean by Blocks at the top is helpful. 

> 
>     * The `Configuration` section should be called `Input file format`

Done

> 
>     * Describe and provide a link to what JSON is

Done

> 
>     * The input file parameter descriptions could be more detailed, what is `fn: Mathematical expression` ?

Will populate this with more info during the JOSS submission reviews. Also removed `fn`. That is part of a future PR that has not been merged yet.
 
> 
>     * Architecture should be under `Developer Guide` and please don't use the `robust architecture` phrase.

Done

> 
> 
> I'm surprised to see `svZeroDGUI` and `svZeroDVisualization` installed under svZeroDSolver, guess I wasn't paying attention to the Issues for this!
> 
> The documentation for these guys needs to be very detailed because they require a bunch of other software installed to run.

**Comment by ktbolt** [comment]
@menon-karthik Very good!

You can use html `<ul>` for bullet points

**Comment by menon-karthik** [comment]
@ktbolt Yup I fixed the bullet points in my last commit. Just `<ul>` does not work for some reason. I had to use `<ul style="list-style-type:disc;">`.

Should I go ahead and merge?
